#!/usr/bin/env python3
"""Generate our schemas from phonetic mappings; no upstream GPL schema is copied."""
from pathlib import Path
import argparse
import json
root = Path(__file__).resolve().parent.parent / 'Vendor/RimeData'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true', help='Fail if checked-in schemas or keycap hints are stale')
args = parser.parse_args()

def emit(path, content):
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f'Stale generated file: {path}; run scripts/generate-rime-schemas.py')
    else:
        path.write_text(content)

common = '''schema:
  schema_id: {schema}
  name: {name}
  version: '1.0'
engine:
  processors: [speller, selector, navigator, express_editor]
  segmentors: [abc_segmentor, fallback_segmentor]
  translators: [script_translator]
menu:
  page_size: 8
speller:
  alphabet: abcdefghijklmnopqrstuvwxyz
  delimiter: " '"
  algebra:
{algebra}
translator:
  dictionary: shika_chinese
  user_dict: pinyin_simp
  prism: {schema}
  enable_user_dict: true
  enable_sentence: true
  max_sentences: 5
  sentence_cutoff_threshold: 0.01
  max_homophones: 8
  enable_completion: true
  spelling_hints: 64
  always_show_comments: true
'''
emit(root/'shika_pinyin.schema.yaml', common.format(schema='shika_pinyin',name='中文全拼',algebra='    - derive/^([nl])ue$/$1ve/\n    - abbrev/^([a-z]).+$/$1/'))
# One phonetic mapping drives both the Rime schema and generated Swift hints.
layout = json.loads((root/'shuangpin-layout.json').read_text())
finals = {final: entry['key'] for entry in layout['keys'] for final in entry['finals']}
initials = {initial: key for key, initial in layout['initials'].items()}
zero = layout['zeroInitials']
syllables=set()
for line in (root/'shika_chinese.dict.yaml').read_text().splitlines():
    fields=line.split('\t')
    if len(fields)>1: syllables.update(fields[1].split())
rules=[]
for syllable in sorted(syllables):
    if syllable in zero: code=zero[syllable]
    else:
        initial=next((s for s in ['zh','ch','sh'] if syllable.startswith(s)),syllable[:1])
        final=syllable[len(initial):]
        if not final: continue
        code=initials.get(initial,initial)+finals.get(final,final)
    if len(code)==2: rules.append(f'    - xform/^{syllable}$/{code.upper()}/')
rules += ['    - xlit/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/']
emit(root/'shika_flypy.schema.yaml', common.format(schema='shika_flypy',name='双拼',algebra='\n'.join(rules)))
emit(root/'default.yaml', 'config_version: "1.0"\nschema_list:\n  - schema: shika_pinyin\n  - schema: shika_flypy\n')

def quoted(value):
    return json.dumps(value, ensure_ascii=False)

# ue and ve share the displayed üe hint; preserve each key's hint order.
hints = {}
for entry in layout['keys']:
    labels = list(dict.fromkeys(final.replace('ue', 've').replace('v', 'ü') for final in entry['finals']))
    hints[entry['key']] = ' / '.join(labels)
swift = [
    'import Foundation', '',
    '/// Generated by scripts/generate-rime-schemas.py. Edit Vendor/RimeData/shuangpin-layout.json.',
    '/// Xiaohe phonetic layout; schema codes and keycap hints share the same source.',
    'enum SKShuangpinLayout {',
    '    static let rows = [' + ', '.join('Array(' + quoted(row) + ')' for row in layout['rows']) + ']',
    '    static let initials: [Character: String] = [' + ', '.join(quoted(k) + ': ' + quoted(v) for k, v in layout['initials'].items()) + ']',
    '    static let finals: [Character: String] = ['
]
swift += ['        ' + quoted(key) + ': ' + quoted(hint) + ',' for key, hint in hints.items()]
swift += ['    ]', '}', '']
emit(root.parent.parent/'ShikaKeyBoard/Schemes/Shuangpin/SKShuangpinLayout.swift', '\n'.join(swift))
print(f'{"Verified" if args.check else "Generated"} {len(rules)-1} Xiaohe syllable mappings and keycap hints')
