#!/usr/bin/env python3
"""Build offline lexicons from pinned upstream data, never from test answers.

Sources are gzip-compressed verbatim snapshots. --fetch restores a missing
snapshot from its pinned HTTPS URL, checking the upstream Git blob digest.
"""
from pathlib import Path
import argparse, array, gzip, hashlib, json, re, struct, subprocess, sys, tempfile, unicodedata

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'Vendor/Lexicons'
OUTPUT = ROOT / 'ShikaKeyBoard/Resources/RimeData.bundle'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--fetch', action='store_true')
parser.add_argument('--import-cache', type=Path)
parser.add_argument('--language', choices=['chinese', 'japanese', 'all'], default='all')
args = parser.parse_args()
lock = json.loads((SOURCE / 'sources.lock.json').read_text())

def source(entry):
    path = SOURCE / entry['archive']
    if not path.exists():
        if args.import_cache:
            data = (args.import_cache / entry['cache']).read_bytes()
        elif args.fetch:
            with tempfile.NamedTemporaryFile() as download:
                subprocess.run(['curl', '-fLsS', '--compressed', '--retry', '3', '--max-time', '300', '-o', download.name, entry['url']], check=True)
                data = Path(download.name).read_bytes()
        else:
            raise SystemExit(f'Missing {path}; restore with --fetch')
        digest = hashlib.sha1(b'blob ' + str(len(data)).encode() + b'\0' + data).hexdigest()
        if digest != entry['gitBlob']:
            raise SystemExit(f'Upstream digest mismatch: {entry["url"]}')
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(gzip.compress(data, mtime=0))
    data = gzip.decompress(path.read_bytes())
    digest = hashlib.sha1(b'blob ' + str(len(data)).encode() + b'\0' + data).hexdigest()
    if digest != entry['gitBlob']:
        raise SystemExit(f'Corrupt source archive: {path}')
    return data.decode('utf-8')

stats = {}
stats_path = OUTPUT / 'lexicon-metadata.json'
if stats_path.exists(): stats = json.loads(stats_path.read_text())

if args.language in ('chinese', 'all'):
    entries = {}
    def normalize(code):
        # Keep ü while removing tone marks, including precomposed ǖ/ǘ/ǚ/ǜ.
        text = unicodedata.normalize('NFD', code)
        text = text.replace('u\u0308', 'v')
        return ''.join(c for c in text if not unicodedata.combining(c)).lower()
    for item in lock['chinese']['files']:
        for line in source(item).splitlines():
            fields = line.split('\t')
            if len(fields) < 3 or not fields[2].strip().isdigit(): continue
            text, code = fields[0], normalize(fields[1])
            if not re.fullmatch('[a-z]+(?: [a-z]+)*', code): continue
            key = (text, code)
            entries[key] = max(entries.get(key, 0), int(fields[2]))
    community_count = len(entries)
    # Preserve legacy coverage, but don't let a differently scaled legacy
    # frequency override the new corpus or dominate its sentence probabilities.
    for line in (ROOT / 'Vendor/RimeData/pinyin_simp.dict.yaml').read_text().splitlines():
        f = line.split('\t')
        if len(f) == 3 and f[2].isdigit(): entries.setdefault((f[0], f[1]), 1)
    target = ROOT / 'Vendor/RimeData/shika_chinese.dict.yaml'
    with target.open('w') as f:
        f.write('# Generated by scripts/prepare-lexicons.py; see Vendor/Lexicons for attribution.\n'
                '---\nname: shika_chinese\nversion: "2026.09.25"\nsort: by_weight\nuse_preset_vocabulary: false\n...\n')
        for (text, code), weight in sorted(entries.items(), key=lambda x: (x[0][1], -x[1], x[0][0])):
            f.write(f'{text}\t{code}\t{weight}\n')
    stats['chinese'] = {'upstream': lock['chinese']['repo'], 'commit': lock['chinese']['commit'],
        'communityEntries': community_count, 'entries': len(entries), 'legacyOnlyEntries': len(entries)-community_count,
        'longEntries': sum(len(code.split()) >= 4 for _, code in entries),
        'sha256': hashlib.sha256(target.read_bytes()).hexdigest()}
    print('Chinese:', stats['chinese'], flush=True)

if args.language in ('japanese', 'all'):
    readings = {}
    for item in lock['japanese']['files']:
        text = source(item)
        if '/dictionary' in item['url'] and re.search(r'dictionary\d\d.txt$', item['url']):
            for line in text.splitlines():
                f = line.split('\t')
                if len(f) < 5: continue
                reading, left, right, cost, surface = f[:5]
                if not reading or not all('\u3041' <= c <= '\u3096' or c == 'ー' for c in reading): continue
                token = (surface, int(left), int(right), int(cost))
                readings.setdefault(reading, set()).add(token)
        elif item['url'].endswith('connection_single_column.txt'):
            values = iter(text.splitlines()); size = int(next(values))
            matrix = array.array('h', (int(v) for v in values))
            if len(matrix) != size * size: raise SystemExit('Invalid Mozc connection matrix size')
            if sys.byteorder != 'little': matrix.byteswap()
            (OUTPUT / 'japanese-connections.bin').write_bytes(b'SKJM' + struct.pack('<I', size) + matrix.tobytes())
        elif item['url'].endswith('romanji-hiragana.tsv'):
            roman = {}
            for line in text.splitlines():
                f = line.split('\t')
                if len(f) >= 2 and re.fullmatch("[a-z'-]+", f[0]):
                    roman[f[0]] = [f[1], f[2] if len(f) > 2 else '']
            (OUTPUT / 'japanese-romaji.json').write_text(json.dumps(roman, ensure_ascii=False, sort_keys=True)+'\n')
    pool = bytearray(); keys = bytearray(); tokens = bytearray(); token_count = 0
    for reading, words in sorted(readings.items(), key=lambda x: x[0].encode('utf8')):
        raw = reading.encode(); offset = len(pool); pool.extend(raw)
        words = sorted(words, key=lambda w: (w[3], w[0], w[1], w[2]))
        keys.extend(struct.pack('<IHHI', offset, len(raw), len(words), token_count))
        for surface, left, right, cost in words:
            raw = surface.encode(); offset = len(pool); pool.extend(raw)
            tokens.extend(struct.pack('<IHHHh', offset, len(raw), left, right, cost)); token_count += 1
    data = b'SKJ1' + struct.pack('<III', len(readings), token_count, 16+len(keys)+len(tokens)) + keys + tokens + pool
    (OUTPUT / 'japanese-lexicon.bin').write_bytes(data)
    stats['japanese'] = {'upstream': lock['japanese']['repo'], 'commit': lock['japanese']['commit'],
        'readings': len(readings), 'entries': token_count, 'bytes': len(data),
        'sha256': hashlib.sha256(data).hexdigest()}
    print('Japanese:', stats['japanese'], flush=True)
stats_path.write_text(json.dumps(stats, ensure_ascii=False, indent=2)+'\n')
